apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: pnc-admin
    name: pnc-admin
  spec:
    replicas: 1
    selector:
      deploymentconfig: pnc-admin
    strategy:
      activeDeadlineSeconds: 21600
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: pnc-admin
      spec:
        containers:
        - image: quay.io/rh-newcastle/pnc-admin:latest
          name: pnc-admin
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        schedulerName: default-scheduler
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pnc-admin
        from:
          kind: ImageStreamTag
          name: pnc-admin:latest
      type: ImageChange
  status: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: pnc-admin
    name: pnc-admin
  spec:
    dockerImageRepository: quay.io/rh-newcastle/pnc-admin
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/rh-newcastle/pnc-admin:latest
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
kind: List
metadata: {}
